# Generated by Django 6.0 on 2026-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('identificacion_usuario', models.BigIntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_retiro', models.DateField()),
                ('vicepresidente', models.CharField(max_length=100)),
                ('gerencia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('canal', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('nro_contrato', models.CharField(max_length=100)),
                ('subcanal', models.CharField(max_length=100)),
                ('punto', models.CharField(max_length=100)),
                ('cc_supervisor', models.CharField(max_length=100)),
                ('lider_etb', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('eps', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('perfil_portal_suma', models.CharField(max_length=100)),
                ('restriccion', models.CharField(max_length=100)),
                ('causa_restriccion', models.CharField(max_length=200)),
                ('id_fibra', models.CharField(max_length=100)),
                ('fija', models.IntegerField()),
                ('movil', models.IntegerField()),
                ('id_cobre', models.IntegerField()),
            ],
        ),
    ]
