# Generated by Django 6.0 on 2026-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('ASESOR', 'Asesor')], default='ASESOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(choices=[('CALDAS', 'Caldas'), ('ANTIOQUIA', 'Antioquia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
    ]
